import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { Window } from 'happy-dom';

const window = new Window({ url: 'http://localhost:5173' });
for (const key of ['window', 'document', 'HTMLElement', 'customElements', 'localStorage', 'Event', 'CustomEvent', 'navigator']) {
  Object.defineProperty(globalThis, key, { configurable: true, value: key === 'window' ? window : window[key] });
}
window.fetch = null; // Component tests never contact household storage.
globalThis.confirm = () => true;
const family = await import('../apps/web/src/stores/family.js');
const chores = await import('../apps/web/src/stores/chores.js');
const balances = await import('../apps/web/src/stores/balances.js');
const rewards = await import('../apps/web/src/stores/rewards.js');
const navigation = await import('../apps/web/src/stores/navigation.js');
const { commit } = await import('../apps/web/src/stores/changes.js');
const view = await import('../apps/web/src/view.js');
const { modal, toastEl, confettiEl, showToast } = await import('../apps/web/src/ui.jsox');
await import('../apps/web/src/app.jsox');
document.body.append(modal, toastEl, confettiEl);
const app = document.createElement('chore-fridge');
document.body.append(app);
const active = () => [...app.children].filter(node => !node.hidden).at(-1);
function click(label, scope = active()) {
  const button = [...scope.querySelectorAll('button')].find(node => node.textContent.trim() === label);
  assert.ok(button, `Button exists: ${label}`);
  assert.equal(button.disabled, false, `Button enabled: ${label}`);
  button.click();
}
function field(label, value, scope = modal) {
  const wrapper = [...scope.querySelectorAll('.field')].find(node => node.querySelector('label')?.textContent === label);
  assert.ok(wrapper, `Field exists: ${label}`);
  wrapper.querySelector('input').value = value;
}
const pauseTap = () => new Promise(resolve => setTimeout(resolve, 290));

after(async () => {
  app.remove();
  clearTimeout(showToast.t);
  await window.happyDOM.abort();
});

test('onboarding, PIN, task editing, completion, rewards, themes, and reconnect', async () => {
  assert.equal(active().localName, 'fridge-setup');
  click('Set up the family');
  field('Name', 'Test Household', active());
  click('Next');
  field("Kid's name", 'Alex', active());
  click('Add kid');
  click('Next');
  field('4-digit PIN', '1234', active());
  click('Open the board');
  assert.equal(active().localName, 'fridge-board');
  assert.match(active().textContent, /Test Household/);
  assert.equal(active().querySelectorAll('fridge-kid').length, 1);
  click('Unlock Parent Mode');
  for (const digit of '0000') click(digit);
  assert.equal(active().localName, 'fridge-pin');
  for (const digit of '1234') click(digit);
  assert.equal(active().localName, 'fridge-board');
  click('Settings');
  assert.equal(active().localName, 'fridge-parent');
  click('Chores');
  click('Add');
  assert.ok(modal.querySelector('.emoji-trigger'), 'Task emoji picker trigger');
  field('Task', 'Wash dishes');
  click('📅 Weekly', modal);
  assert.equal(modal.querySelector('fridge-choices').value, 'weekly');
  click('Save', modal);
  assert.equal(chores.$chores.get()[0].repeat, 'weekly');
  assert.equal(chores.$chores.get()[0].title, 'Wash dishes');
  click('Close');
  const column = active().querySelector('fridge-kid');
  const row = column.querySelector('fridge-chore');
  row.querySelector('button').click();
  assert.equal(balances.starsFor(family.$kids.get()[0].id), 5);
  assert.match(row.querySelector('button').className, /done/);
  assert.equal(active().querySelector('fridge-kid'), column);
  assert.equal(column.querySelector('fridge-chore'), row);
  await pauseTap();
  row.querySelector('button').click();
  assert.equal(balances.starsFor(family.$kids.get()[0].id), 0);
  await pauseTap();
  row.querySelector('button').click();
  rewards.saveReward({ id:'reward', title:'Treat', emoji:'🎁', cost:5, gold:false });
  active().querySelector('.reward').click();
  modal.querySelector('.choice').click();
  assert.equal(balances.starsFor(family.$kids.get()[0].id), 0);
  rewards.saveReward({ ...rewards.$rewards.get()[0], title:'Updated treat' });
  assert.match(active().querySelector('.reward').textContent, /Updated treat/);
  click('View');
  click('Dark', modal);
  click('Cyberpunk', modal);
  assert.equal(document.documentElement.dataset.look, 'cyberpunk');
  assert.equal(document.documentElement.classList.contains('night'), true);
  modal.querySelector('[aria-label="Zoom in"]').click();
  assert.equal(view.getView().zoom, 110);
  click('Done', modal);
  click('View');
  assert.equal(modal.querySelector('.zoom-val').textContent, '110%');
  click('Done', modal);
  const childCount = app.children.length;
  app.remove();
  document.body.append(app);
  assert.equal(app.children.length, childCount);
  assert.equal(active().querySelector('fridge-kid'), column);
  assert.equal(column.querySelectorAll('fridge-chore').length, 1);
});

test('counted chores, multiple assignments, keyed reorder/removal, and empty board', async () => {
  const first = family.$kids.get()[0];
  const second = { id:'second', name:'Sam', emoji:'🐸', color:'#2a9d8f' };
  family.saveKid(second);
  const chore = chores.saveChore({ title:'Practice', kidIds:[first.id, second.id], points:2, minCount:2, maxCount:3, gold:true });
  const board = active().querySelector('.board');
  const columns = [...board.children];
  const row = columns[0].querySelector(`[data-key="${chore.id}"]`);
  await pauseTap();
  row.querySelector('button').click();
  assert.equal(chores.countFor(chore, first.id), 1);
  assert.equal(chores.isDone(chore, first.id), false);
  await pauseTap();
  row.querySelector('button').click();
  assert.equal(chores.isDone(chore, first.id), true);
  assert.equal(chores.countFor(chore, second.id), 0);
  await pauseTap();
  row.querySelector('.mark').click();
  assert.equal(chores.countFor(chore, first.id), 1);
  assert.equal(balances.goldFor(first.id), 2);
  commit(() => family.$kids.set([...family.$kids.get()].reverse()));
  assert.equal(board.children[0], columns[1]);
  assert.equal(board.children[1], columns[0]);
  family.removeKid(second.id);
  assert.equal(board.children.length, 1);
  assert.equal(board.children[0], columns[0]);
  chores.removeChore(chore.id);
  assert.equal(row.isConnected, false);
  family.removeKid(first.id);
  assert.match(board.textContent, /No kids yet/);
  assert.equal(board.children.length, 1);
});

test('task form tabs cover weekday daily, weekly one-claim, once archive, and every', async () => {
  const alex = { id:'tab-alex', name:'Alex', emoji:'🐻', color:'#e85d4c' };
  const sam = { id:'tab-sam', name:'Sam', emoji:'🐸', color:'#2a9d8f' };
  family.saveKid(alex);
  family.saveKid(sam);
  navigation.setUI({ view:'parent', parentUnlocked:true, parentTab:'chores' });
  click('Add');
  assert.ok(modal.querySelector('#task-form-tabs'));
  field('Task', 'Trash night');
  click('📅 Weekly', modal);
  assert.equal(modal.querySelector('[role="tab"][aria-selected="true"]').textContent.trim(), 'Weekly');
  modal.querySelector('input[aria-label="Only allow one claim per week"]').click();
  click('Save', modal);
  const weekly = chores.$chores.get().find(item => item.title === 'Trash night');
  assert.equal(weekly.repeat, 'weekly');
  assert.equal(weekly.sharedClaim, true);
  navigation.setUI({ view:'board', parentUnlocked:true });
  const alexRow = [...active().querySelectorAll('fridge-kid')].find(node => node.textContent.includes('Alex')).querySelector(`[data-key="${weekly.id}"]`);
  const samRow = [...active().querySelectorAll('fridge-kid')].find(node => node.textContent.includes('Sam')).querySelector(`[data-key="${weekly.id}"]`);
  await pauseTap();
  alexRow.querySelector('button').click();
  assert.equal(chores.isDone(weekly, alex.id), true);
  assert.equal(chores.isDone(weekly, sam.id), true);
  assert.equal(samRow.querySelector('button').disabled, true);
  const once = chores.saveChore({ title:'Party setup', kidIds:[alex.id], repeat:'once', points:1 });
  await pauseTap();
  [...active().querySelectorAll('fridge-kid')].find(node => node.textContent.includes('Alex')).querySelector(`[data-key="${once.id}"] button`).click();
  assert.equal(chores.$chores.get().some(item => item.id === once.id), false);
  const every = chores.saveChore({ title:'Water plants', kidIds:[alex.id], repeat:'every', everyN:3, everyUnit:'days', points:1 });
  assert.equal(every.repeat, 'every');
  assert.equal(every.everyN, 3);
  assert.equal(every.everyUnit, 'days');
  chores.$chores.get().slice().forEach(item => chores.removeChore(item.id));
  family.removeKid(alex.id);
  family.removeKid(sam.id);
});

test('multiple view controls stay synchronized and removed controls unsubscribe', () => {
  const one = document.createElement('fridge-view-controls');
  const two = document.createElement('fridge-view-controls');
  document.body.append(one, two);
  view.setLook('modern');
  const tint = one.querySelector('.look-modern-split input[type="color"]');
  assert.ok(one.querySelector('.look-modern-split.on'));
  tint.value = '#8033cc';
  tint.dispatchEvent(new Event('input',{bubbles:true}));
  assert.equal(two.querySelector('input[type="color"]').value,'#8033cc');
  assert.equal(JSON.parse(localStorage.getItem(view.VIEW_KEY)).modernColor,'#8033cc');
  assert.equal(document.documentElement.style.getPropertyValue('--modern-hue'),'270');
  assert.equal(document.documentElement.style.getPropertyValue('--modern-accent-sat'),'60%');
  view.setLook('classic');
  assert.equal(tint.closest('.look-modern-split').hidden,false);
  assert.equal(one.querySelector('.look-modern-split.on'),null);
  view.setTheme('light');
  click('Dark', one);
  const selected = two.querySelector('button[aria-pressed="true"]');
  assert.equal(selected.textContent, 'Dark');
  one.remove();
  view.setZoom(150);
  assert.equal(two.querySelector('[aria-label="Zoom in"]').disabled, true);
  assert.notEqual(one.querySelector('.zoom-val').textContent, '150%');
  document.body.append(one);
  assert.equal(one.querySelector('.zoom-val').textContent, '150%');
  assert.equal(one.querySelectorAll('.zoom-row').length, 1);
  view.setLayout('gallery');
  assert.equal(two.querySelector('.view-layouts button[aria-pressed="true"]').textContent.trim(), 'Gallery');
  view.setLayout('classic');
  one.remove();
  two.remove();
});

test('board layouts switch between classic columns, gallery cards, and slide-to-shop', () => {
  view.setLayout('classic');
  assert.equal(document.documentElement.dataset.layout, 'classic');
  assert.equal(active().querySelector('fridge-shop').hidden, true);
  view.setLayout('gallery');
  assert.equal(document.documentElement.dataset.layout, 'gallery');
  const shop = active().querySelector('fridge-shop');
  assert.equal(shop.hidden, false);
  assert.match(shop.textContent, /The Shop/);
  assert.equal(active().querySelector('.dock').hidden, true);
  view.setLayout('slide');
  const saying = active().querySelector('.shop-saying');
  assert.ok(saying);
  assert.ok(saying.textContent.trim().length > 0);
  assert.equal(active().querySelector('.slide-go-shop').hidden, false);
  active().querySelector('.slide-go-shop').click();
  assert.equal(active().querySelector('.workspace').classList.contains('shop-open'), true);
  assert.equal(active().querySelector('.slide-go-board').hidden, false);
  active().querySelector('.slide-go-board').click();
  assert.equal(active().querySelector('.workspace').classList.contains('shop-open'), false);
  assert.equal(JSON.parse(localStorage.getItem(view.VIEW_KEY)).layout, 'slide');
  view.setLayout('classic');
  assert.equal(active().querySelector('fridge-shop').hidden, true);
});

test('store snapshots and computed balances stay consistent without a refresh call', () => {
  const kid = { id:'reactive', name:'Riley', emoji:'🐻', color:'#e85d4c' };
  const before = family.$kids.get();
  family.saveKid(kid);
  assert.equal(before.length, 0);
  assert.equal(family.$kids.get().length, 1);
  assert.match(active().textContent, /Riley/);
  navigation.setUI({ view:'parent', parentTab:'kids' });
  const settings = active().querySelector('fridge-kids-settings');
  const row = settings.querySelector('fridge-kid-settings');
  const edit = row.querySelector('button');
  family.saveKid({ ...kid, name:'Renamed Riley' });
  assert.equal(settings.querySelector('fridge-kid-settings'), row);
  assert.equal(row.querySelector('button'), edit);
  assert.match(row.textContent, /Renamed Riley/);
  navigation.setUI({ parentTab:'display' });
  const display = active().querySelector('fridge-view-controls');
  family.saveKid({ ...kid, name:'Riley' });
  assert.equal(active().querySelector('fridge-view-controls'), display);
  navigation.setUI({ parentTab:'kids' });
  assert.equal(active().querySelector('fridge-kids-settings'), settings);
  app.remove();
  family.saveKid({ ...kid, name:'While disconnected' });
  assert.doesNotMatch(row.textContent, /While disconnected/);
  document.body.append(app);
  assert.match(row.textContent, /While disconnected/);
  navigation.setUI({ view:'board' });
});

test('reward and PIN edits do not touch existing chore DOM', () => {
  const kid = family.$kids.get()[0];
  chores.saveChore({ title:'Stable DOM', kidIds:[kid.id], points:1 });
  const column = active().querySelector('fridge-kid');
  const observer = new window.MutationObserver(() => {});
  observer.observe(column, { childList:true, subtree:true, attributes:true, characterData:true });
  rewards.saveReward({ id:'isolated-reward', title:'Separate reward', cost:10 });
  family.setPin('5678');
  assert.equal(observer.takeRecords().length, 0);
  observer.disconnect();
});

test('archive and restore controls retain earned credit on a versioned board', async () => {
  const { applySnapshot, defaultState } = await import('../apps/web/src/stores/sync.js');
  const { initializeTaskHistory } = await import('@chore-fridge/domain/task-history');
  applySnapshot(initializeTaskHistory({...defaultState(),setupDone:true,kids:[{id:'history-kid',name:'Alex'}],chores:[
    {id:'first-task',title:'First inserted',kidIds:['history-kid'],points:1,repeat:'weekly'},
    {id:'history-task',title:'Keep my credit',kidIds:['history-kid'],points:2,repeat:'daily'},
    {id:'last-task',title:'Last inserted',kidIds:['history-kid'],points:1,repeat:'once'},
  ],completions:{'2026-09-07:history-task:history-kid':1}}));
  navigation.unlockParent();
  navigation.setUI({view:'parent',parentTab:'chores'});
  const rows = [...active().querySelectorAll('fridge-task-summary')];
  assert.deepEqual(rows.map(row => row.querySelector('.grow > div').textContent),[
    'First inserted · Weekly','Keep my credit · Daily','Last inserted · Once',
  ]);
  click('Archive',rows[1]);
  assert.equal(chores.$chores.get().length,2);
  assert.equal(balances.starsFor('history-kid'),2);
  const row = active().querySelector('fridge-archived-task');
  assert.match(row.textContent,/Keep my credit/);
  click('Restore',row);
  assert.equal(chores.$chores.get().at(-1).taskId,'history-task');
  assert.equal(chores.$archivedChores.get().length,0);
  assert.equal(balances.starsFor('history-kid'),2);
});

test('parent unlock lasts across navigation, explicit lock closes editors, and PIN changes relock', () => {
  family.setPin('2468');
  navigation.lockParent();
  click('Unlock Parent Mode');
  click('1');
  click('Back to board');
  assert.equal(navigation.$ui.get().pinBuf,'');
  assert.equal(navigation.$ui.get().parentUnlocked,false);
  click('Unlock Parent Mode');
  for (const digit of '0000') click(digit);
  assert.equal(navigation.$ui.get().parentUnlocked,false);
  for (const digit of '2468') click(digit);
  assert.equal(active().localName,'fridge-board');
  click('Settings');
  assert.equal(active().localName,'fridge-parent');
  assert.equal(active().getAttribute('role'),'dialog');
  assert.equal(active().getAttribute('aria-modal'),'true');
  const boardScreen = [...app.children].find(node => node.localName === 'fridge-board');
  assert.equal(boardScreen.hidden,false);
  assert.equal(boardScreen.inert,true);
  const tabs = active().querySelector('fridge-tabs');
  assert.equal(tabs.getAttribute('role'),'tablist');
  assert.equal(tabs.querySelectorAll('[role="tab"]').length,8);
  assert.equal(tabs.querySelector('[role="tab"]').getAttribute('aria-controls'),'settings-panel');
  assert.equal(tabs.querySelector('[aria-selected="true"]').textContent.toLowerCase(),navigation.$ui.get().parentTab);
  for (const page of ['General','Kids','Chores','Rewards','Currency','Display','Advanced','Help']) {
    click(page);
    assert.ok(active().querySelector('.settings-body .lead'),`${page} has a subtitle`);
  }
  click('Display');
  tabs.querySelector('[aria-selected="true"]').dispatchEvent(new window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));
  assert.equal(tabs.querySelector('[aria-selected="true"]').textContent,'Advanced');
  click('Display');
  assert.ok(active().querySelector('.settings-body fridge-view-controls'));
  assert.equal(active().querySelector('button.look-classic').textContent.trim(),'Classic (V1)');
  const modern = active().querySelector('.look-modern-split');
  assert.ok(modern);
  assert.ok(modern.querySelector('button.look-modern'));
  assert.ok(modern.querySelector('input[type="color"][aria-label="Modern theme color"]'));
  assert.equal(active().querySelectorAll('.modern-color').length,0);
  assert.equal([...active().querySelectorAll('button')].some(button => button.textContent.trim() === 'Change PIN'),false);
  assert.equal([...active().querySelectorAll('button')].some(button => button.textContent.trim() === 'Erase board and start over'),false);
  assert.equal(modal.hidden,true);
  assert.equal([...active().querySelectorAll('button')].some(button => button.textContent.trim() === 'View'),false);
  click('General');
  assert.equal([...active().querySelectorAll('.settings-group > h3')].filter(heading => heading.textContent === 'Permissions').length,1);
  assert.equal(active().querySelectorAll('.settings-stack .setting-toggle').length,2);
  const nameInput = active().querySelector('input[aria-label="Household name"]');
  nameInput.value = 'The Test House';
  click('Save');
  assert.equal(family.$familyName.get(),'The Test House');
  const sayingsInput = active().querySelector('textarea[aria-label="Shop sayings"]');
  assert.ok(sayingsInput);
  assert.match(sayingsInput.value,/Stars well earned/);
  sayingsInput.value = '  Hello from the shop  \n\nSecond line\n';
  click('Save sayings');
  assert.deepEqual(family.$sayings.get(),['Hello from the shop','Second line']);
  click('Restore defaults');
  assert.ok(family.$sayings.get().includes('Stars well earned are stars well spent.'));
  assert.ok([...active().querySelectorAll('button')].find(button => button.textContent.trim() === 'Change PIN'));
  assert.ok([...active().querySelectorAll('button')].find(button => button.textContent.trim() === 'Erase board and start over'));
  click('Advanced');
  const mcpToggle = active().querySelector('input[aria-label="Enable MCP"]');
  assert.ok(mcpToggle);
  assert.equal(active().querySelector('.mcp-connection').hidden,true);
  mcpToggle.click();
  assert.equal(family.$mcpEnabled.get(),true);
  assert.equal(active().querySelector('.mcp-connection').hidden,false);
  assert.match(active().querySelector('input[aria-label="MCP URL"]').value,/\/mcp$/);
  assert.match(active().querySelector('.setting-details pre').textContent,/chore-fridge/);
  mcpToggle.click();
  assert.equal(family.$mcpEnabled.get(),false);
  click('Currency');
  const coinToggle = active().querySelector('input[aria-label="Enable Coin"]');
  assert.ok(coinToggle);
  coinToggle.click();
  assert.equal(family.$currencies.get().find(item => item.id === 'coin').enabled, true);
  const coinName = active().querySelector('input[aria-label="Coin name"]');
  coinName.value = 'Tokens';
  coinName.parentElement.querySelector('button').click();
  assert.equal(family.$currencies.get().find(item => item.id === 'coin').name, 'Tokens');
  click('Close');
  assert.match(active().textContent,/The Test House/);
  assert.equal(boardScreen.inert,false);
  assert.equal(navigation.$ui.get().parentUnlocked,true);
  click('Settings');
  assert.equal(active().localName,'fridge-parent');
  click('Lock Parent Mode');
  assert.equal(active().localName,'fridge-board');
  navigation.setUI({view:'parent'});
  assert.equal(active().localName,'fridge-board');
  navigation.setUI({view:'board'});
  click('Unlock Parent Mode');
  for (const digit of '2468') click(digit);
  click('Settings');
  click('Chores');
  click('Add');
  assert.equal(modal.hidden,false);
  family.setPin('1357');
  assert.equal(navigation.$ui.get().parentUnlocked,false);
  assert.equal(active().localName,'fridge-board');
  assert.equal(modal.hidden,true);
  assert.equal(modal.children.length,0);
  family.setPin('');
  click('Unlock Parent Mode');
  assert.equal(active().localName,'fridge-board');
  click('Settings');
  assert.equal(active().localName,'fridge-parent');
  click('Close');
  click('Lock Parent Mode');
  assert.equal(navigation.$ui.get().parentUnlocked,false);
});

test('completion setting blocks normal and counted tasks while locked and displays a message', async () => {
  const sync = await import('../apps/web/src/stores/sync.js');
  const changes = await import('../apps/web/src/stores/changes.js');
  const task = {id:'gated-task',title:'Task',kidIds:['gated-kid'],points:2,repeat:'daily',minCount:1,maxCount:1};
  sync.applySnapshot({...sync.defaultState(),setupDone:true,kids:[{id:'gated-kid',name:'Alex'}],chores:[task,{...task,id:'gated-count',title:'Counted task',maxCount:3}]});
  navigation.lockParent();
  click('Unlock Parent Mode');
  assert.equal(active().localName,'fridge-board');
  click('Settings');
  click('General');
  const checkbox = active().querySelector('fridge-general-settings input');
  checkbox.checked = true;
  checkbox.dispatchEvent(new Event('change',{bubbles:true}));
  assert.equal(checkbox.getAttribute('role'),'switch');
  assert.equal(checkbox.getAttribute('aria-checked'),'true');
  assert.equal(active().querySelector('.setting-status').textContent,'On');
  assert.equal(family.$requireParentModeForCompletion.get(),true);
  assert.equal(sync.serializeHousehold().requireParentModeForCompletion,true);
  click('Close');
  click('Lock Parent Mode');
  const revision = changes.$revision.get();
  for (const row of active().querySelectorAll('fridge-chore')) {
    row.querySelector('button').click();
    assert.equal(toastEl.textContent,'Unlock Parent Mode to change task completion.');
  }
  assert.deepEqual(chores.$completions.get(),{});
  assert.deepEqual(chores.$counts.get(),{});
  assert.equal(changes.$revision.get(),revision);
  click('Unlock Parent Mode');
  await pauseTap();
  const plain = [...active().querySelectorAll('fridge-chore')].find(row => !row.textContent.includes('Counted task'));
  plain.querySelector('button').click();
  assert.equal(chores.isDone(chores.$chores.get()[0],'gated-kid'),true);
  await pauseTap();
  const counted = [...active().querySelectorAll('fridge-chore')].find(row => row.textContent.includes('Counted task'));
  counted.querySelector('button').click();
  assert.equal(chores.countFor(chores.$chores.get()[1],'gated-kid'),1);
  click('Lock Parent Mode');
  const lockedRevision = changes.$revision.get();
  const creditsBefore = balances.starsFor('gated-kid');
  plain.querySelector('button').click();
  assert.equal(toastEl.textContent,'Unlock Parent Mode to change task completion.');
  counted.querySelector('.mark').click();
  assert.equal(toastEl.textContent,'Unlock Parent Mode to change task completion.');
  assert.equal(chores.isDone(chores.$chores.get()[0],'gated-kid'),true);
  assert.equal(chores.countFor(chores.$chores.get()[1],'gated-kid'),1);
  assert.equal(balances.starsFor('gated-kid'),creditsBefore);
  assert.equal(changes.$revision.get(),lockedRevision);
  click('Unlock Parent Mode');
  await pauseTap();
  plain.querySelector('button').click();
  assert.equal(chores.isDone(chores.$chores.get()[0],'gated-kid'),false);
  await pauseTap();
  counted.querySelector('.mark').click();
  assert.equal(chores.countFor(chores.$chores.get()[1],'gated-kid'),0);
  click('Settings');
  click('General');
  const control = active().querySelector('fridge-general-settings input');
  control.checked = false;
  control.dispatchEvent(new Event('change',{bubbles:true}));
  click('Close');
  click('Lock Parent Mode');
  await pauseTap();
  counted.querySelector('button').click();
  assert.equal(chores.countFor(chores.$chores.get()[1],'gated-kid'),1);
});

test('redemption toggle independently blocks spending while locked and shows a message', async () => {
  const sync = await import('../apps/web/src/stores/sync.js');
  const changes = await import('../apps/web/src/stores/changes.js');
  sync.applySnapshot({...sync.defaultState(),setupDone:true,requireParentModeForCompletion:true,kids:[{id:'reward-kid',name:'Alex'}],chores:[{id:'earned',title:'Task',points:10,kidIds:['reward-kid'],repeat:'daily'},{id:'gold-task',title:'Gold task',points:1,gold:true,kidIds:['reward-kid'],repeat:'daily'}],completions:{'2026-09-06:earned:reward-kid':1,'2026-09-06:gold-task:reward-kid':1},rewards:[{id:'stars',title:'Star reward',emoji:'⭐',cost:2},{id:'gold',title:'Gold reward',emoji:'⭐',cost:1,gold:true}]});
  navigation.unlockParent();
  click('Settings');
  click('General');
  const toggle = active().querySelector('input[aria-label="Require Parent Mode for redemptions"]');
  toggle.click();
  assert.equal(toggle.getAttribute('aria-checked'),'true');
  assert.equal(family.$requireParentModeForCompletion.get(),true);
  assert.equal(family.$requireParentModeForRedemptions.get(),true);
  click('Close');
  click('Lock Parent Mode');
  const revision = changes.$revision.get();
  active().querySelector('.reward').click();
  assert.equal(toastEl.textContent,'Unlock Parent Mode to redeem rewards.');
  assert.equal(modal.hidden,true);
  for (const id of ['stars','gold']) assert.match(rewards.redeemReward(id,'reward-kid').error,/Unlock Parent Mode/);
  assert.equal(changes.$revision.get(),revision);
  assert.equal(balances.starsFor('reward-kid'),10);
  assert.equal(balances.goldFor('reward-kid'),1);
  click('Unlock Parent Mode');
  assert.equal(rewards.redeemReward('gold','reward-kid').ok,true);
  assert.equal(balances.goldFor('reward-kid'),0);
  click('Settings');
  click('General');
  active().querySelector('input[aria-label="Require Parent Mode for redemptions"]').click();
  assert.equal(family.$requireParentModeForCompletion.get(),true);
  click('Close');
  click('Lock Parent Mode');
  assert.equal(rewards.redeemReward('stars','reward-kid').ok,true);
  assert.equal(balances.starsFor('reward-kid'),8);
});
