import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { Window } from 'happy-dom';

const window = new Window({ url: 'http://localhost:5173' });
for (const key of ['window', 'document', 'HTMLElement', 'customElements', 'localStorage', 'Event', 'CustomEvent', 'navigator']) {
  Object.defineProperty(globalThis, key, { configurable: true, value: key === 'window' ? window : window[key] });
}
window.fetch = null; // Component tests never contact household storage.
globalThis.confirm = () => true;
const family = await import('../apps/web/src/stores/family.js');
const chores = await import('../apps/web/src/stores/chores.js');
const balances = await import('../apps/web/src/stores/balances.js');
const rewards = await import('../apps/web/src/stores/rewards.js');
const navigation = await import('../apps/web/src/stores/navigation.js');
const { commit } = await import('../apps/web/src/stores/changes.js');
const view = await import('../apps/web/src/view.js');
const { modal, toastEl, confettiEl, showToast } = await import('../apps/web/src/ui.jsox');
await import('../apps/web/src/app.jsox');
document.body.append(modal, toastEl, confettiEl);
const app = document.createElement('chore-fridge');
document.body.append(app);
const active = () => [...app.children].find(node => !node.hidden);
function click(label, scope = active()) {
  const button = [...scope.querySelectorAll('button')].find(node => node.textContent.trim() === label);
  assert.ok(button, `Button exists: ${label}`);
  assert.equal(button.disabled, false, `Button enabled: ${label}`);
  button.click();
}
function field(label, value, scope = modal) {
  const wrapper = [...scope.querySelectorAll('.field')].find(node => node.querySelector('label')?.textContent === label);
  assert.ok(wrapper, `Field exists: ${label}`);
  wrapper.querySelector('input').value = value;
}
const pauseTap = () => new Promise(resolve => setTimeout(resolve, 290));

after(async () => {
  app.remove();
  clearTimeout(showToast.t);
  await window.happyDOM.abort();
});

test('onboarding, PIN, task editing, completion, rewards, themes, and reconnect', async () => {
  assert.equal(active().localName, 'fridge-setup');
  click('Set up the family');
  field('Name', 'Test Household', active());
  click('Next');
  field("Kid's name", 'Alex', active());
  click('Add kid');
  click('Next');
  field('4-digit PIN', '1234', active());
  click('Open the board');
  assert.equal(active().localName, 'fridge-board');
  assert.match(active().textContent, /Test Household/);
  assert.equal(active().querySelectorAll('fridge-kid').length, 1);
  click('Unlock Parent Mode');
  for (const digit of '0000') click(digit);
  assert.equal(active().localName, 'fridge-pin');
  for (const digit of '1234') click(digit);
  assert.equal(active().localName, 'fridge-board');
  click('Settings');
  assert.equal(active().localName, 'fridge-parent');
  click('Chores');
  click('Add');
  field('Task', 'Wash dishes');
  click('📅 Once a week', modal);
  assert.equal(modal.querySelector('fridge-choices').value, 'weekly');
  click('Save', modal);
  assert.equal(chores.$chores.get()[0].repeat, 'weekly');
  assert.equal(chores.$chores.get()[0].title, 'Wash dishes');
  click('Board');
  const column = active().querySelector('fridge-kid');
  const row = column.querySelector('fridge-chore');
  row.querySelector('button').click();
  assert.equal(balances.starsFor(family.$kids.get()[0].id), 5);
  assert.match(row.querySelector('button').className, /done/);
  assert.equal(active().querySelector('fridge-kid'), column);
  assert.equal(column.querySelector('fridge-chore'), row);
  await pauseTap();
  row.querySelector('button').click();
  assert.equal(balances.starsFor(family.$kids.get()[0].id), 0);
  await pauseTap();
  row.querySelector('button').click();
  rewards.saveReward({ id:'reward', title:'Treat', emoji:'🎁', cost:5, gold:false });
  active().querySelector('.reward').click();
  modal.querySelector('.choice').click();
  assert.equal(balances.starsFor(family.$kids.get()[0].id), 0);
  rewards.saveReward({ ...rewards.$rewards.get()[0], title:'Updated treat' });
  assert.match(active().querySelector('.reward').textContent, /Updated treat/);
  click('View');
  click('Dark', modal);
  click('Cyberpunk', modal);
  assert.equal(document.documentElement.dataset.look, 'cyberpunk');
  assert.equal(document.documentElement.classList.contains('night'), true);
  modal.querySelector('[aria-label="Zoom in"]').click();
  assert.equal(view.getView().zoom, 110);
  click('Done', modal);
  click('View');
  assert.equal(modal.querySelector('.zoom-val').textContent, '110%');
  click('Done', modal);
  const childCount = app.children.length;
  app.remove();
  document.body.append(app);
  assert.equal(app.children.length, childCount);
  assert.equal(active().querySelector('fridge-kid'), column);
  assert.equal(column.querySelectorAll('fridge-chore').length, 1);
});

test('counted chores, multiple assignments, keyed reorder/removal, and empty board', async () => {
  const first = family.$kids.get()[0];
  const second = { id:'second', name:'Sam', emoji:'🐸', color:'#2a9d8f' };
  family.saveKid(second);
  const chore = chores.saveChore({ title:'Practice', kidIds:[first.id, second.id], points:2, minCount:2, maxCount:3, gold:true });
  const board = active().querySelector('.board');
  const columns = [...board.children];
  const row = columns[0].querySelector(`[data-key="${chore.id}"]`);
  await pauseTap();
  row.querySelector('button').click();
  assert.equal(chores.countFor(chore, first.id), 1);
  assert.equal(chores.isDone(chore, first.id), false);
  await pauseTap();
  row.querySelector('button').click();
  assert.equal(chores.isDone(chore, first.id), true);
  assert.equal(chores.countFor(chore, second.id), 0);
  await pauseTap();
  row.querySelector('.mark').click();
  assert.equal(chores.countFor(chore, first.id), 1);
  assert.equal(balances.goldFor(first.id), 1);
  commit(() => family.$kids.set([...family.$kids.get()].reverse()));
  assert.equal(board.children[0], columns[1]);
  assert.equal(board.children[1], columns[0]);
  family.removeKid(second.id);
  assert.equal(board.children.length, 1);
  assert.equal(board.children[0], columns[0]);
  chores.removeChore(chore.id);
  assert.equal(row.isConnected, false);
  family.removeKid(first.id);
  assert.match(board.textContent, /No kids yet/);
  assert.equal(board.children.length, 1);
});

test('multiple view controls stay synchronized and removed controls unsubscribe', () => {
  const one = document.createElement('fridge-view-controls');
  const two = document.createElement('fridge-view-controls');
  document.body.append(one, two);
  view.setTheme('light');
  click('Dark', one);
  const selected = two.querySelector('button[aria-pressed="true"]');
  assert.equal(selected.textContent, 'Dark');
  one.remove();
  view.setZoom(150);
  assert.equal(two.querySelector('[aria-label="Zoom in"]').disabled, true);
  assert.notEqual(one.querySelector('.zoom-val').textContent, '150%');
  document.body.append(one);
  assert.equal(one.querySelector('.zoom-val').textContent, '150%');
  assert.equal(one.querySelectorAll('.zoom-row').length, 1);
  one.remove();
  two.remove();
});

test('store snapshots and computed balances stay consistent without a refresh call', () => {
  const kid = { id:'reactive', name:'Riley', emoji:'🐻', color:'#e85d4c' };
  const before = family.$kids.get();
  family.saveKid(kid);
  assert.equal(before.length, 0);
  assert.equal(family.$kids.get().length, 1);
  assert.match(active().textContent, /Riley/);
  navigation.setUI({ view:'parent', parentTab:'kids' });
  const settings = active().querySelector('fridge-kids-settings');
  const row = settings.querySelector('fridge-kid-settings');
  const edit = row.querySelector('button');
  family.saveKid({ ...kid, name:'Renamed Riley' });
  assert.equal(settings.querySelector('fridge-kid-settings'), row);
  assert.equal(row.querySelector('button'), edit);
  assert.match(row.textContent, /Renamed Riley/);
  navigation.setUI({ parentTab:'display' });
  const display = active().querySelector('fridge-view-controls');
  family.saveKid({ ...kid, name:'Riley' });
  assert.equal(active().querySelector('fridge-view-controls'), display);
  navigation.setUI({ parentTab:'kids' });
  assert.equal(active().querySelector('fridge-kids-settings'), settings);
  app.remove();
  family.saveKid({ ...kid, name:'While disconnected' });
  assert.doesNotMatch(row.textContent, /While disconnected/);
  document.body.append(app);
  assert.match(row.textContent, /While disconnected/);
  navigation.setUI({ view:'board' });
});

test('reward and PIN edits do not touch existing chore DOM', () => {
  const kid = family.$kids.get()[0];
  chores.saveChore({ title:'Stable DOM', kidIds:[kid.id], points:1 });
  const column = active().querySelector('fridge-kid');
  const observer = new window.MutationObserver(() => {});
  observer.observe(column, { childList:true, subtree:true, attributes:true, characterData:true });
  rewards.saveReward({ id:'isolated-reward', title:'Separate reward', cost:10 });
  family.setPin('5678');
  assert.equal(observer.takeRecords().length, 0);
  observer.disconnect();
});

test('archive and restore controls retain earned credit on a versioned board', async () => {
  const { applySnapshot, defaultState } = await import('../apps/web/src/stores/sync.js');
  const { initializeTaskHistory } = await import('@chore-fridge/domain/task-history');
  applySnapshot(initializeTaskHistory({...defaultState(),setupDone:true,kids:[{id:'history-kid',name:'Alex'}],chores:[{id:'history-task',title:'Keep my credit',kidIds:['history-kid'],points:2,repeat:'daily'}],completions:{'2026-09-07:history-task:history-kid':1}}));
  navigation.unlockParent();
  navigation.setUI({view:'parent',parentTab:'chores'});
  click('Archive',active().querySelector('fridge-task-summary'));
  assert.equal(chores.$chores.get().length,0);
  assert.equal(balances.starsFor('history-kid'),2);
  const row = active().querySelector('fridge-archived-task');
  assert.match(row.textContent,/Keep my credit/);
  click('Restore',row);
  assert.equal(chores.$chores.get()[0].taskId,'history-task');
  assert.equal(chores.$archivedChores.get().length,0);
  assert.equal(balances.starsFor('history-kid'),2);
});

test('parent unlock lasts across navigation, explicit lock closes editors, and PIN changes relock', () => {
  family.setPin('2468');
  navigation.lockParent();
  click('Unlock Parent Mode');
  click('1');
  click('Back to board');
  assert.equal(navigation.$ui.get().pinBuf,'');
  assert.equal(navigation.$ui.get().parentUnlocked,false);
  click('Unlock Parent Mode');
  for (const digit of '0000') click(digit);
  assert.equal(navigation.$ui.get().parentUnlocked,false);
  for (const digit of '2468') click(digit);
  assert.equal(active().localName,'fridge-board');
  click('Settings');
  assert.equal(active().localName,'fridge-parent');
  click('Board');
  assert.equal(navigation.$ui.get().parentUnlocked,true);
  click('Settings');
  assert.equal(active().localName,'fridge-parent');
  click('Lock Parent Mode');
  assert.equal(active().localName,'fridge-board');
  navigation.setUI({view:'parent'});
  assert.equal(active().localName,'fridge-board');
  navigation.setUI({view:'board'});
  click('Unlock Parent Mode');
  for (const digit of '2468') click(digit);
  click('Settings');
  click('Chores');
  click('Add');
  assert.equal(modal.hidden,false);
  family.setPin('1357');
  assert.equal(navigation.$ui.get().parentUnlocked,false);
  assert.equal(active().localName,'fridge-board');
  assert.equal(modal.hidden,true);
  assert.equal(modal.children.length,0);
  family.setPin('');
  click('Unlock Parent Mode');
  assert.equal(active().localName,'fridge-board');
  click('Settings');
  assert.equal(active().localName,'fridge-parent');
  click('Board');
  click('Lock Parent Mode');
  assert.equal(navigation.$ui.get().parentUnlocked,false);
});

test('completion setting blocks normal and counted tasks while locked and displays a message', async () => {
  const sync = await import('../apps/web/src/stores/sync.js');
  const changes = await import('../apps/web/src/stores/changes.js');
  const task = {id:'gated-task',title:'Task',kidIds:['gated-kid'],points:2,repeat:'daily',minCount:1,maxCount:1};
  sync.applySnapshot({...sync.defaultState(),setupDone:true,kids:[{id:'gated-kid',name:'Alex'}],chores:[task,{...task,id:'gated-count',title:'Counted task',maxCount:3}]});
  navigation.lockParent();
  click('Unlock Parent Mode');
  assert.equal(active().localName,'fridge-board');
  click('Settings');
  click('General');
  const checkbox = active().querySelector('fridge-general-settings input');
  checkbox.checked = true;
  checkbox.dispatchEvent(new Event('change',{bubbles:true}));
  assert.equal(checkbox.getAttribute('role'),'switch');
  assert.equal(checkbox.getAttribute('aria-checked'),'true');
  assert.equal(active().querySelector('.setting-status').textContent,'On');
  assert.equal(family.$requireParentModeForCompletion.get(),true);
  assert.equal(sync.serializeHousehold().requireParentModeForCompletion,true);
  click('Board');
  click('Lock Parent Mode');
  const revision = changes.$revision.get();
  for (const row of active().querySelectorAll('fridge-chore')) {
    row.querySelector('button').click();
    assert.equal(toastEl.textContent,'Unlock Parent Mode to change task completion.');
  }
  assert.deepEqual(chores.$completions.get(),{});
  assert.deepEqual(chores.$counts.get(),{});
  assert.equal(changes.$revision.get(),revision);
  click('Unlock Parent Mode');
  await pauseTap();
  const plain = [...active().querySelectorAll('fridge-chore')].find(row => !row.textContent.includes('Counted task'));
  plain.querySelector('button').click();
  assert.equal(chores.isDone(chores.$chores.get()[0],'gated-kid'),true);
  await pauseTap();
  const counted = [...active().querySelectorAll('fridge-chore')].find(row => row.textContent.includes('Counted task'));
  counted.querySelector('button').click();
  assert.equal(chores.countFor(chores.$chores.get()[1],'gated-kid'),1);
  click('Lock Parent Mode');
  const lockedRevision = changes.$revision.get();
  const creditsBefore = balances.starsFor('gated-kid');
  plain.querySelector('button').click();
  assert.equal(toastEl.textContent,'Unlock Parent Mode to change task completion.');
  counted.querySelector('.mark').click();
  assert.equal(toastEl.textContent,'Unlock Parent Mode to change task completion.');
  assert.equal(chores.isDone(chores.$chores.get()[0],'gated-kid'),true);
  assert.equal(chores.countFor(chores.$chores.get()[1],'gated-kid'),1);
  assert.equal(balances.starsFor('gated-kid'),creditsBefore);
  assert.equal(changes.$revision.get(),lockedRevision);
  click('Unlock Parent Mode');
  await pauseTap();
  plain.querySelector('button').click();
  assert.equal(chores.isDone(chores.$chores.get()[0],'gated-kid'),false);
  await pauseTap();
  counted.querySelector('.mark').click();
  assert.equal(chores.countFor(chores.$chores.get()[1],'gated-kid'),0);
  click('Settings');
  click('General');
  const control = active().querySelector('fridge-general-settings input');
  control.checked = false;
  control.dispatchEvent(new Event('change',{bubbles:true}));
  click('Board');
  click('Lock Parent Mode');
  await pauseTap();
  counted.querySelector('button').click();
  assert.equal(chores.countFor(chores.$chores.get()[1],'gated-kid'),1);
});
